#pragma once

#include "madbfs/path.hpp"
#include "madbfs/stat.hpp"
#include "madbfs/transport/transport.hpp"

#include <madbfs-common/async/async.hpp>
#include <madbfs-common/log.hpp>

#include <saf.hpp>

namespace madbfs::path
{
    class Path;
    class PathBuf;
}

namespace madbfs
{
    /**
     * @class ParsedStat
     *
     * @brief Parsed `Stat` value and the filename in question.
     *
     * This struct is used for `statdir` operation. It represent a file entry (name only, not full path) and
     * its stat.
     */
    struct ParsedStat
    {
        Stat stat;
        Str  name;
    };

    namespace connection_strategy
    {
        /**
         * @class Proxy
         *
         * @brief Connection strategy that uses the proxy or when it is unavailable, delegate to Adb.
         *
         * Proxy -> Adb -> Null
         */
        struct Proxy
        {
            Opt<path::PathBuf> server;
            u16                port;
        };

        /**
         * @class Adb
         *
         * @brief Connection strategy that only uses Adb.
         *
         * Adb -> Null
         */
        struct Adb
        {
        };

        /**
         * @class Null
         *
         * @brief Empty connection.
         */
        struct Null
        {
        };

        /**
         * @class Custom
         *
         * The connection will always use the transport generated by the function provided by this strategy.
         * Useful for testing.
         */
        struct Custom
        {
            std::function<Uniq<transport::Transport>()> create;
        };
    }

    /**
     * @class Proxy
     *
     * @brief Connection strategy to be used for connection.
     */
    struct ConnectionStrategy    //
        : util::VarWrapper<      //
              connection_strategy::Proxy,
              connection_strategy::Adb,
              connection_strategy::Null,
              connection_strategy::Custom>
    {
        using VarWrapper::VarWrapper;
    };

    /**
     * @class Connection
     *
     * @brief Abstract struct for connection to adb devices and its fs operations.
     */
    class Connection
    {
    public:
        Connection() = delete;

        Connection(Connection&&)            = delete;
        Connection& operator=(Connection&&) = delete;

        Connection(const Connection&)            = delete;
        Connection& operator=(const Connection&) = delete;

        ~Connection();

        Connection(async::Context& ctx, ConnectionStrategy strat);

        /**
         * @brief Start the connection.
         */
        Await<void> start();

        /**
         * @brief Get connection name.
         */
        Str name() const;

        /**
         * @brief Cancel all pending operations that go through this connection.
         *
         * @param err The error status to be set for cancelled operations.
         */
        void cancel(Errc err);

        /**
         * @brief Check if connection is at the optimum of the strategy used for the transport.
         */
        bool is_optimal() const;

        /**
         * @brief Try to optimize the connection by using the most optimized transport.
         *
         * If the call to optimize is successful, the `Connection` is in stopped state, call `start()` again
         * in that case.
         */
        AExpect<void> optimize();

        /**
         * @brief Try to reconnect using the set strategy of the connection.
         *
         * If reconnection is successful, the `Connection` is in stopped state, call `start()` again in that
         * case.
         */
        AExpect<void> reconnect();

        /**
         * @brief Check if connection is alive.
         *
         * @param timeout Time until the check fail and the connection is dead.
         */
        AExpect<void> ping(Opt<Seconds> timeout);

        // directory operations
        // --------------------

        /**
         * @brief List
         *
         * @param path Path to a directory.
         *
         * @return A generator if successful, or an error if it fails.
         */
        AExpect<Gen<ParsedStat>> statdir(path::Path path);

        /**
         * @brief Get the stat of a file or directory.
         *
         * @param path The path to the file or directory.
         *
         * @return The stat of the file or directory.
         */
        AExpect<Stat> stat(path::Path path);

        /**
         * @brief Get the real file pointed by a symlink.
         *
         * @param path The path to the file or directory.
         *
         * The returned path may be relative so it's not safe to directly convert it to `path::path` or
         * `path::PathBuf`, use `path::resolve()` instead in that case.
         */
        AExpect<String> readlink(path::Path path);

        /**
         * @brief Create a new empty file.
         *
         * @param path Path of the new file.
         */
        AExpect<void> mknod(path::Path path, mode_t mode, dev_t dev);

        /**
         * @brief Make a directory on the device.
         *
         * @param path Path to the directory.
         */
        AExpect<void> mkdir(path::Path path, mode_t mode);

        /**
         * @brief Remove a file on the device.
         *
         * @param path Path to the file on the device.
         * @param bool Whether to remove recursively or not.
         */
        AExpect<void> unlink(path::Path path);

        /**
         * @brief Remove a directory on the device.
         *
         * @param path Path to the directory on the device.
         */
        AExpect<void> rmdir(path::Path path);

        /**
         * @brief Move a file on the device.
         *
         * @param from Target file.
         * @param to Destination file.
         */
        AExpect<void> rename(path::Path from, path::Path to, u32 flags);

        // --------------------

        // file operations
        // ---------------

        /**
         * @brief Truncate a file on the device.
         *
         * @param path Path to the file on the device.
         * @param size Size to truncate to.
         */
        AExpect<void> truncate(path::Path path, off_t size);

        /**
         * @brief Update change time and modification time of a file
         *
         * @param path Path to the file on the device.
         * @param atime Access time.
         * @param mtime Modification time.
         */
        AExpect<void> utimens(path::Path path, timespec atime, timespec mtime);

        /**
         * @brief Copy file server-side.
         *
         * @param in Input file path.
         * @param in_off Input offset.
         * @param out Output file path.
         * @param out_off Output offset.
         * @param size Number of bytes to be copied.
         */
        AExpect<usize> copy_file_range(
            path::Path in,
            off_t      in_off,
            path::Path out,
            off_t      out_off,
            usize      size
        );

        /**
         * @brief Open a file from the device.
         *
         * @param path Path to the file on the device.
         * @param mode Mode in which the file will be opened.
         */
        AExpect<u64> open(path::Path path, OpenMode mode);

        /**
         * @brief Close a file descriptor.
         *
         * @param fd File descriptor to a file on the device.
         */
        AExpect<void> close(u64 fd);

        /**
         * @brief Read from a file on the device.
         *
         * @param fd File descriptor to a file on the device.
         * @param out Buffer to read into.
         * @param offset Offset to read from.
         */
        AExpect<usize> read(u64 fd, Span<char> out, off_t offset);

        /**
         * @brief Write to a file on the device.
         *
         * @param fd File descriptor to a file on the device.
         * @param in Buffer to write from.
         * @param offset Offset to write to.
         */
        AExpect<usize> write(u64 fd, Span<const char> in, off_t offset);

        // ---------------
    private:
        /**
         * @brief Check if reconnection is in progress and then wait for the result.
         *
         * If there is no reconnection, this function will immediately return `std::nullopt`, on successful
         * reconnection, the function will return default value of `Errc` (0; success).
         */
        Await<Opt<Errc>> check_reconnection();

        /**
         * @brief Send request through the transport but wait for reconnection if one is ongoing.
         *
         * @param buf Data buffer.
         * @param req Operation request.
         */
        template <rpc::IsRequest Req>
        AExpect<rpc::ToResp<Req>> send_req(Req req)
        {
            constexpr auto max_attempts = 5uz;

            auto attempt = 0uz;
            while (attempt++ < max_attempts) {
                auto resp = co_await m_transport->send_req(std::move(req));
                if (resp) {
                    co_return resp;
                }

                if (auto err = resp.error(); err == Errc::resource_unavailable_try_again) {
                    auto res = co_await check_reconnection();
                    if (res == std::nullopt or res != Errc{}) {
                        co_return resp;
                    }
                } else {
                    co_return resp;
                }

                log_d("{}: reconnection for req at attempt: {}", __func__, attempt);
                // reconnection complete, try again
            }

            // give up if too many attempts
            co_return Unexpect{ Errc::timed_out };
        }

        Uniq<transport::Transport> m_transport;
        ConnectionStrategy         m_strategy;

        Opt<saf::shared_future<Errc>> m_reconnection;
    };
}
