name: madbfs CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'      # only for semantic versioning
  pull_request:
    branches: [ "main" ]

env:
  NDK_VERSION: 29.0.13599879
  SDK_MANAGER: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager
  ANDROID_NDK_HOME_BASE: /usr/local/lib/android/sdk/ndk

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure C++ Development Tools
      run: |
        sudo apt install gcc-14 g++-14 cmake ninja-build git

    - name: Configure Conan 2 Package Manager
      run: |
        sudo apt install python3 python3-pip
        pip3 install conan
        conan profile detect --force
      env:
        CC: gcc-14
        CXX: g++-14

    - name: Configure Android NDK
      run: |
        yes | $SDK_MANAGER --licenses > /dev/null
        $SDK_MANAGER --install "ndk;$NDK_VERSION"
        echo ANDROID_NDK_HOME="$ANDROID_NDK_HOME_BASE/$NDK_VERSION" >> $GITHUB_ENV

    - name: Build, Test, and Package
      run: ./package.sh "$PWD/.github/ci/conan-profile.ini"

    - name: Save Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: madbfs
        path: ./build/package/madbfs.tar.gz

# todo: add filesystem test job (requires android emulation to exist)
