name: madbfs CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'      # only for semantic versioning
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup conan client
      uses: conan-io/setup-conan@v1
      with:
        version: 2.29.0
        cache_packages: true
        profile_detect: true

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.10

    - name: Configure C++ development tools
      run: sudo apt-get install cmake ninja-build

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r29

    - name: Build, Test, and Package
      run: ./build.sh --package
      env:
        ANDROID_NDK_HOME: "${{ steps.setup-ndk.outputs.ndk-path }}"
        SCCACHE_GHA_ENABLED: true
        CMAKE_C_COMPILER_LAUNCHER: "sccache"
        CMAKE_CXX_COMPILER_LAUNCHER: "sccache"

    - name: Save Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: madbfs
        path: |
          ./build/package-Release-Release/madbfs.tar.gz
          ./build/package-Release-Release/madbfs.tar.gz.sha256

  filesystem_test:
    needs: build
    runs-on: ubuntu-26.04
    env:
      API_LEVEL: 30
      MADBFS_BINARY_PATH: /usr/local/bin/madbfs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get madbfs
      uses: actions/download-artifact@v4
      with:
        name: madbfs

    - name: Copy madbfs to system bin directory
      run: |
        tar -xf madbfs.tar.gz --directory=/tmp madbfs/madbfs
        sudo cp /tmp/madbfs/madbfs ${{ env.MADBFS_BINARY_PATH }}
        sudo chmod +x ${{ env.MADBFS_BINARY_PATH }}

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ env.API_LEVEL }}

    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: Run filesystem test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
          export ANDROID_SERIAL=$(adb devices | head -n2 | tail -n1 | cut -f1)
          pip install pytest
          pytest -x ./test/test_filesystem.py

    - name: Save test logs
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: ./test/log/

